SAMPLE_RATE    = 16000
FFT_SIZE       = 512
HOP_LENGTH     = 64
EPOCHS         = 200
BATCH_SIZE     = 32
CONTEXT_FRAMES = 8

N_FREQ_BINS = FFT_SIZE // 2 + 1   # 257
BAND_SIZE   = 8
NUM_BANDS   = (N_FREQ_BINS + BAND_SIZE - 1) // BAND_SIZE   # 33
PADDED_FREQ = NUM_BANDS * BAND_SIZE                        # 264

VAL_SEED = 42
